---
- name: Install homedir
  git: repo="git@github.com:{{git_username}}/homedir.git"
       dest="{{homedir}}/{{username}}/{{personal_dir}}/homedir"
       accept_hostkey=True
  tags:
    - homedir
    - repos

- name: Symlink dot files
  file: src="{{homedir}}/{{username}}/{{personal_dir}}/homedir/{{item}}"
        dest="{{homedir}}/{{username}}/{{item}}"
        owner="{{username}}"
        group="{{usergroup}}"
        state=link
  with_items:
    - .ackrc
    - .bash
    - .bash_profile
    - .bashrc
    - .gdbinit
    - .gemrc
    - .gitconfig
    - .gitignore_global
    - .hgrc
    - .inputrc
    - .ipython
    - .irbrc
    - .screenrc
    - .tmux.conf
    - .vim
    - .vimrc
    - bin
  tags:
    - homedir
    - links
    - vim

- name: Install Vim Syntastic
  git: repo="git@github.com:/{{item.user}}/{{item.repo}}.git"
       dest="{{homedir}}/{{username}}/.vim/bundle/{{item.repo}}"
       accept_hostkey=True
  with_items:
    - {user: scrooloose, repo: syntastic}
    - {user: scrooloose, repo: nerdtree}
  tags:
    - homedir
    - repos
    - vim
