---
- name: Install python versions (2.X)
  command: "pyenv install -s {{item}}"
  environment:
    CC: "{{cc}}"
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
    PYTHON_CONFIGURE_OPTS: "{{pyflags}} --enable-framework=/Users/{{username}}/.pyenv/versions/{{item}}"
  with_items:
    - 2.7.15

- name: Install python versions (3.X)
  command: "pyenv install -s {{item}}"
  environment:
    CC: "{{cc}}"
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
    PYTHON_CONFIGURE_OPTS: "{{pyflags}} --enable-framework=/Users/{{username}}/.pyenv/versions/{{item}}"
  with_items:
    - 3.7.2

- name: Set global python
  command: "pyenv global {{versions | join(' ')}}"

- name: Uninstall old python versions
  command: "pyenv uninstall -f {{item}}"
  with_items:
    - 2.6.9
    - 2.7.11
    - 2.7.12
    - 2.7.13
    - 2.7.14
    - 3.3.6
    - 3.4.4
    - 3.4.5
    - 3.4.6
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.6.1
    - 3.6.5

- name: Install Crypto Packages (2.7)
  pip:
    name:
      - cryptography
    state: latest
    executable: "/Users/{{username}}/.pyenv/shims/pip2.7"
  environment:
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"

- name: Install Python Packages (2.7)
  pip:
    name:
      - pip
      - virtualenv
      - ansible
      - awacs
      - awscli
      - boto
      - boto3
      - flake8
      - ipython
      - isort
      - powerline-status
      - tox
      - troposphere
      - yapf
    state: latest
    executable: "/Users/{{username}}/.pyenv/shims/pip2.7"

- name: Install Python Science Packages (2.7)
  pip:
    name:
      - numpy
      - scipy
      - matplotlib
      - pandas
      - jupyter
    state: latest
    executable: "/Users/{{username}}/.pyenv/shims/pip2.7"

- name: Install Python Packages (3.7)
  pip:
    name:
      - flake8
      - ipython
      - isort
      - powerline-status
      - tox
      - yapf
    state: latest
    executable: "/Users/{{username}}/.pyenv/shims/{{item}}"
  with_items:
    - pip3.7
