---
- name: Install python versions
  command: "pyenv install -s {{item}}"
  with_items: "{{ versions }}"

- name: Set global python
  command: "pyenv global {{versions | join(' ')}}"

- name: Install Python Packages
  pip: name="{{item}}"
       state=latest
       executable=/Users/christophergi/.pyenv/shims/pip2.7
  with_items:
    - pip
    - virtualenv
    - awscli
    - boto
    - flake8
    - ipython
    - isort
    - tox
    - troposphere
    - yapf
