---
- name: Install python versions (2.X)
  command: "pyenv install -s {{item}}"
  environment:
    CC: "{{cc}}"
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
    PYTHON_CONFIGURE_OPTS: "{{pyflags}} --enable-framework=/Users/{{username}}/.pyenv/versions/{{item}}"
  with_items:
    - 2.7.13

- name: Install python versions (3.X)
  command: "pyenv install -s {{item}}"
  environment:
    CC: "{{cc}}"
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
    PYTHON_CONFIGURE_OPTS: "{{pyflags}} --enable-framework=/Users/{{username}}/.pyenv/versions/{{item}}"
  with_items:
    - 3.5.2
    - 3.4.5

- name: Install python version (3.3)
  command: "pyenv install -s {{item}}"
  environment:
    CC: "{{cc}}"
  with_items:
    - 3.3.6

- name: Set global python
  command: "pyenv global {{versions | join(' ')}}"

- name: Uninstall old python versions
  command: "pyenv uninstall -f {{item}}"
  with_items:
    - 3.5.1
    - 3.4.4
    - 2.7.12
    - 2.7.11
    - 2.6.9

- name: Install Crypto Packages (2.7)
  pip: name="{{item}}"
       state=latest
       executable="/Users/{{username}}/.pyenv/shims/pip2.7"
  environment:
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
  with_items:
    - cryptography

- name: Install Python Packages (2.7)
  pip: name="{{item}}"
       state=latest
       executable="/Users/{{username}}/.pyenv/shims/pip2.7"
  with_items:
    - pip
    - virtualenv
    - ansible
    - awscli
    - boto
    - flake8
    - ipython
    - isort
    - tox
    - troposphere
    - yapf

- name: Install Python Science Packages (2.7)
  pip: name="{{item}}"
       state=latest
       executable="/Users/{{username}}/.pyenv/shims/pip2.7"
  with_items:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - jupyter

- name: Install Python Packages (3.5, 3.4)
  pip: name="{{item[1]}}"
       state=latest
       executable="/Users/{{username}}/.pyenv/shims/{{item[0]}}"
  with_nested:
    - ['pip3.5', 'pip3.4']
    - ['flake8', 'ipython', 'isort', 'tox', 'yapf']
