---
- name: Install python versions (2.7.12)
  command: "pyenv install -s {{item}}"
  environment:
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
    PYTHON_CONFIGURE_OPTS: "--enable-unicode=ucs2 --framework"
  with_items:
    - 2.7.12

- name: Install python versions (3.5.1, 3.4.4)
  command: "pyenv install -s {{item}}"
  environment:
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
  with_items:
    - 3.5.1
    - 3.4.4

- name: Install python versions
  command: "pyenv install -s {{item}}"
  with_items:
    - 3.3.6
    - 2.6.9

- name: Set global python
  command: "pyenv global {{versions | join(' ')}}"

- name: Uninstall old python versions
  command: "pyenv uninstall -f {{item}}"
  with_items:
    - 2.7.11

- name: Install Crypto Packages (2.7.12)
  pip: name="{{item}}"
       state=latest
       executable=/Users/christophergi/.pyenv/shims/pip2.7
  environment:
    CFLAGS: "{{cflags}}"
    LDFLAGS: "{{ldflags}}"
  with_items:
    - cryptography

- name: Install Python Packages (2.7.12)
  pip: name="{{item}}"
       state=latest
       executable=/Users/christophergi/.pyenv/shims/pip2.7
  with_items:
    - pip
    - virtualenv
    - ansible
    - awscli
    - boto
    - flake8
    - ipython
    - isort
    - matlpotlib
    - numpy
    - scipy
    - tox
    - troposphere
    - yapf

- name: Install Python Packages (3.5)
  pip: name="{{item[1]}}"
       state=latest
       executable="/Users/christophergi/.pyenv/shims/{{item[0]}}"
  with_nested:
    - ['pip3.5', 'pip3.4']
    - ['flake8', 'ipython', 'isort', 'tox', 'yapf']
