# CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include"
# LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib"

cflags: -I/usr/local/opt/readline/include -I/usr/local/opt/openssl@1.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
ldflags: -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib
pyflags: --enable-framework
cc: clang
versions:
  - 3.8.0
  - 2.7.17
