cflags: -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include
ldflags: -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib
pyflags: --enable-framework
cc: clang
versions:
  - 2.7.13
  - 3.6.1
  - 3.5.3
  - 3.4.6
  - 3.3.6
