---
- homebrew: name=autoconf
- homebrew: name=git
- homebrew: name=ipcalc
- homebrew: name=jq
- homebrew: name=node
- homebrew: name=openssl
- homebrew: name=pkg-config
- homebrew: name=pwgen
- homebrew: name=pyenv
- homebrew: name=readline
- homebrew: name=readline
- homebrew: name=ssh-copy-id
- homebrew: name=vim
- homebrew: name=wget
- homebrew: update_homebrew=yes upgrade_all=yes
