---
- name: Manage local computer
  vars_files:
    - ../group_vars/all.yml
  hosts: localhost
  roles:
    - {role: common, tags: ['common']}
    - {role: osx, tags: ['osx']}
    - {role: homedir, tags: ['homedir']}
